name: 'awasome semver action'
description: 'calculated new version'
branding:
  icon: 'book'  
  color: 'red'
outputs:
  version:
    description: 'The value of the new pre-calculated tag'
    value: ${{steps.versioning.outputs.version}}
  previous-version:
    description: 'Contains the value of previous tag, before calculating a new one'
    value: ${{steps.versioning.outputs.previous-version}}
runs:
  using: 'composite'
  steps:
  - name: checkout
    uses: actions/checkout@v3
    with:
      fetch-depth: 0
  - name: versioning
    shell: bash
    run: node main.js
