on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: run this action for test
    steps:
      - name: versioning
        id: versioning
        uses: allnnde/semver-action@v1.0

      - name: Get the output time
        run: echo "version ${{ steps.versioning.outputs.version }} previous version version ${{ steps.versioning.outputs.previous-version }}"
        