on: [push]

jobs:
  calculate:
    runs-on: ubuntu-latest
    name: run
    outputs:
      version: ${{steps.versioning.outputs.version}}
    steps:
      - name: versioning
        id: versioning
        uses: allnnde/semver-action@v1.1.1   

  show:
    runs-on: ubuntu-latest
    needs: calculate
    name: run
    steps:
      - name: get versions values
        run: echo version ${{needs.calculate.outputs.version}}!
        