on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: run
    steps:
      - name: versioning
        id: versioning
        uses: allnnde/semver-action@v1.1.1
      - name: get versions values
        run: echo version ${{ steps.versioning.outputs.version }}! previous version ${{ steps.versioning.outputs.previous-version }}!!
        